name: penetration security scans for sql injection
on: push
jobs:
  pen_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Run pen scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://3.141.0.47:8989/WebGoat'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
